### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by slothking87** [LeighCurran/AuroraPlusHA#8]
Hi there 

Does this still work? We recently signed up for Aurora+ and would love to integrate it into HA. 

I have followed the instructions and am getting these errors. Does anyone have any suggestions on what I have done wrong? 

auroraplus: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 570, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 942, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/auroraplus/sensor.py", line 161, in update
    self._state = round(float(self._session.EstimatedBalance),self._rounding)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'api' object has no attribute 'EstimatedBalance'

auroraplus: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 570, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 942, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/auroraplus/sensor.py", line 154, in update
    self._session.getsummary()
  File "/usr/local/lib/python3.11/site-packages/auroraplus/__init__.py", line 61, in getsummary
    summarydata = self.request("day")
                  ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/auroraplus/__init__.py", line 52, in request
    request = self.session.get(self.url + '/usage/' + timespan +'?serviceAgreementID=' + self.serviceAgreementID + '&customerId=' + self.customerId + '&index=-1', headers={'Authorization': self.token})
                                                                                         ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'api' object has no attribute 'serviceAgreementID'

**Comment by slothking87** [comment]
Errors corrected by resetting password
